apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: myapp
type: Opaque
stringData:
  APP_KEY: "base64:zeFRWnWnci42SKhsVIqhH9l9nE6m+Wl9Ukq4Mc8D7wA="
  DB_USERNAME: laravel_user
  DB_PASSWORD: laravel_password
