apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migrate
  namespace: myapp
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: praktikan/bridgeops-ai:latest
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - configMapRef:
                name: laravel-config
            - secretRef:
                name: laravel-secret
